import { createNamespace } from '../namespace';

export const RDF = createNamespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#', [
  'Alt',
  'Bag',
  'CompoundLiteral',
  'direction',
  'first',
  'HTML',
  'JSON',
  'langString',
  'language',
  'List',
  'nil',
  'object',
  'PlainLiteral',
  'predicate',
  'Property',
  'rest',
  'Seq',
  'Statement',
  'subject',
  'type',
  'value',
  'XMLLiteral',
]);
