export const FOCUSABLE_ELEMENTS_SELECTOR = [
  'a[href]',
  'area[href]',
  'button:not([disabled])',
  'embed',
  'iframe',
  'input:not([disabled])',
  'object',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '*[tabindex]:not([aria-disabled]):not([tabindex="-1"])',
  '*[contenteditable]',
  'details:not([disabled])',
  'summary:not(:disabled)',
].join(',');
