name: build-and-test

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main, alpha, beta]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 18.15.x
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      # root deps
      - name: Cache node modules root
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-root
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
      - name: Install root dependencies
        run: npm i
      # cli deps
      - name: Cache node modules cli
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-cli
        with:
          path: ./libs/cli/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./libs/cli/package-lock.json') }}
      - name: Install cli dependencies
        run: npm i
        working-directory: ./libs/cli
      # docs deps
      # - name: Cache node modules docs
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules-docs
      #   with:
      #     path: ./apps/docs/node_modules
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./apps/docs/package-lock.json') }}
      # - name: Install docs dependencies
      #   run: npm i
      #   working-directory: ./apps/docs
      #- run: npm run affected:lint -- --base=origin/main
      - run: npm run nx -- run-many --target=build --configuration=production --exclude=docs,docs-app
      - run: npm run nx -- run-many --target=test --exclude=docs,docs-app
      #- run: npm run affected:e2e -- --headless --base=origin/main
